SECRET_KEY = 'DUMMYKEY(for development)DUMMYKEY(for development)'

# [mode]
DEBUG = true

# [site]
# The URL of this site, used in links in emails and in the redirect URL for
# OAuth 2.0 services. (This value should end with a forward slash.)
SITE_URL = "localhost:8040/"
ALLOWED_HOSTS = []

# [installation]
# The name of the institution, to be included in the notification signoff
NOTIFICATION_INSTITUTION = 'MAGENTA APS'

# [email]
DEFAULT_FROM_EMAIL = "os2datascanner@magenta.dk"
ADMIN_EMAIL = "os2datascanner@magenta.dk"
EMAIL_HOST = "localhost"
EMAIL_PORT = 25

[DATABASES]

    [DATABASES.default]
    ENGINE = "django.db.backends.postgresql_psycopg2"
    NAME = "os2datascanner_report"
    USER = "os2datascanner_report_dev"
    PASSWORD = "os2datascanner_report_dev"
    HOST = "db"

# The full documentation can be found here: https://github.com/fangli/django-saml2-auth
[SAML2_AUTH]

# Metadata is required, choose either remote url or local file path
METADATA_AUTO_CONF_URL = '[The auto(dynamic) metadata configuration URL of SAML2]'
METADATA_LOCAL_FILE_PATH = '[The metadata configuration file path]'

# Optional settings below
DEFAULT_NEXT_URL = '/admin'  # Custom target redirect URL after the user get logged in. Default to /admin if not set. This setting will be overwritten if you have parameter ?next= specificed in the login URL.
CREATE_USER = 'TRUE' # Create a new Django user when a new user logs in. Defaults to True.
ASSERTION_URL = 'https://mysite.com' # Custom URL to validate incoming SAML requests against
ENTITY_ID = 'https://mysite.com/saml2_auth/acs/' # Populates the Issuer element in authn request
NAME_ID_FORMAT = 'FormatString' # Sets the Format property of authn NameIDPolicy element
USE_JWT = false # Set this to True if you are running a Single Page Application (SPA) with Django Rest Framework (DRF), and are using JWT authentication to authorize client users
FRONTEND_URL = 'https://myfrontendclient.com' # Redirect URL for the client if you are using JWT auth with DRF. See explanation below

    [SAML2_AUTH.NEW_USER_PROFILE]
    USER_GROUPS = []  # The default group name when a new user logs in
    ACTIVE_STATUS = true  # The default active status for new users
    STAFF_STATUS = true  # The staff status for new users
    SUPERUSER_STATUS = false  # The superuser status for new users

    [SAML2_AUTH.ATTRIBUTES_MAP]
    # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
    email = 'Email'
    username = 'UserName'
    first_name = 'FirstName'
    last_name = 'LastName'

    [SAML2_AUTH.TRIGGER]
    CREATE_USER = 'path.to.your.new.user.hook.method'
    BEFORE_LOGIN = 'path.to.your.login.hook.method'
