SECRET_KEY = "DUMMYKEY(for testing)DUMMYKEY(for testing)"

[DATABASES]

    [DATABASES.default]
    ENGINE = "django.db.backends.postgresql_psycopg2"
    NAME = "os2datascanner_report"
    USER = "os2datascanner_report_test"
    PASSWORD = "os2datascanner_report_test"
    HOST = "postgres"
