################################################################################
# Changes to this file requires approval from Labs. Please add a person from   #
# Labs as required approval to your MR if you have any changes.                #
################################################################################

# For the release steps to work, the following envionment variables have to set
# in the Gitlab UI:
# RELEASE_REGISTRY_USER
# RELEASE_REGISTRY_PASSWORD


stages:
  - lint
  - build
  - test
  - release


variables:
  # Project variables
  RELEASE_REGISTRY: docker.io
  RELEASE_REPORT_IMAGE: index.docker.io/magentaaps/os2datascanner-report
  RELEASE_ADMIN_IMAGE: index.docker.io/magentaaps/os2datascanner-admin
  RELEASE_ENGINE_IMAGE: index.docker.io/magentaaps/os2datascanner-engine

  REPORT_IMAGE: ${CI_REGISTRY_IMAGE}/report:${CI_COMMIT_SHA}
  ADMIN_IMAGE: ${CI_REGISTRY_IMAGE}/admin:${CI_COMMIT_SHA}
  ENGINE_IMAGE: ${CI_REGISTRY_IMAGE}/engine:${CI_COMMIT_SHA}


# Lint stage
#############

.lint-default: &lint-default
  stage: lint
  needs: []
  services: []
  tags:
    - docker
  allow_failure: false

Lint Python:
  <<: *lint-default
  image: python:3.6
  before_script:
    - pip install flake8
  script:
    - flake8 --version
    - flake8 src/
  allow_failure: true

Lint Dockerfiles:
  <<: *lint-default
  image: hadolint/hadolint:latest-debian
  before_script:
    - apt-get -y update
    - apt-get -y install --no-install-recommends git
  script:
    - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 hadolint

Lint shell scripts:
  <<: *lint-default
  image: koalaman/shellcheck-alpine:latest
  before_script:
    - apk update
    - apk add git
  script:
    - git ls-files --exclude='*.sh' --ignored | xargs shellcheck
  allow_failure: true


# Build stage
##############

.build-default: &build-default
  stage: build
  needs: []
  services: []
  image:
    # We use kaniko v0.16.0 as both v0.17.0, v0.17.1, v0.18.0 and v0.19.0
    # contains fatal bugs.
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  tags:
    - docker
  allow_failure: false

Build Report Application:
  <<: *build-default
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache
      --context=$CI_PROJECT_DIR
      --dockerfile=$CI_PROJECT_DIR/docker/report/Dockerfile
      --destination=${REPORT_IMAGE}

Build Admin Application:
  <<: *build-default
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache
      --context=$CI_PROJECT_DIR
      --dockerfile=$CI_PROJECT_DIR/docker/admin/Dockerfile
      --destination=${ADMIN_IMAGE}

Build Engine:
  <<: *build-default
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache
      --context=$CI_PROJECT_DIR
      --dockerfile=$CI_PROJECT_DIR/docker/engine/Dockerfile
      --destination=${ENGINE_IMAGE}

Build documentation:
  <<: *build-default
  image: keimlink/sphinx-doc:latex
  script:
    - make -C doc PAPER=a4 html latexpdf
    - mv doc/_build .
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - _build


# Test stage
#############

.test-default: &test-default
  stage: test
  tags:
    - docker
    - network-per-build
  services:
    - postgres:12
    - rabbitmq:3-alpine
  variables:
    POSTGRES_HOST: postgres
    AMQP_HOST: rabbitmq
    AMQP_USER: guest
    AMQP_PWD: guest
    SECRET_KEY: TestDummy!TestDummy!TestDummy!TestDummy!TestDummy!
    COVERAGE_FILE: $CI_PROJECT_DIR/.coverage
  allow_failure: false

Test Admin Application:
  extends: .test-default
  image:
    name: ${ADMIN_IMAGE}
  variables:
    POSTGRES_DB: os2datascanner_admin
    POSTGRES_USER: os2datascanner_admin
    POSTGRES_PASSWORD: os2datascanner_admin
    DECRYPTION_FILE_PATH: ${CI_PROJECT_DIR}/dev-environment/admin
  needs:
    - Build Admin Application
  script:
    - coverage run --source=os2datascanner.projects.admin,os2datascanner.utils, -m django test os2datascanner.projects.admin.tests
  after_script:
    - coverage html -d ${CI_PROJECT_DIR}/coverage-html
    - coverage xml -o ${CI_PROJECT_DIR}/junit.xml
    - coverage report
  coverage: '/^TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/coverage-html
    reports:
      junit: $CI_PROJECT_DIR/junit.xml

Test Engine:
  extends: .test-default
  image:
    name: ${ENGINE_IMAGE}
  needs:
    - Build Engine
  script:
    - coverage run --source=os2datascanner.engine2,os2datascanner.utils, -m unittest discover -s /code/src/os2datascanner/engine2/tests
  after_script:
    - coverage html -d ${CI_PROJECT_DIR}/coverage-html
    - coverage xml -o ${CI_PROJECT_DIR}/junit.xml
    - coverage report
  coverage: '/^TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/coverage-html
    reports:
      junit: $CI_PROJECT_DIR/junit.xml

Test Report Application:
  extends: .test-default
  image:
    name: ${REPORT_IMAGE}
  variables:
    POSTGRES_DB: os2datascanner_report
    POSTGRES_USER: os2datascanner_report
    POSTGRES_PASSWORD: os2datascanner_report
  needs:
    - Build Report Application
  script:
    - coverage run --source=os2datascanner.projects.report,os2datascanner.utils, -m django test os2datascanner.projects.report.tests
  after_script:
    - coverage html -d ${CI_PROJECT_DIR}/coverage-html
    - coverage xml -o ${CI_PROJECT_DIR}/junit.xml
    - coverage report
  coverage: '/^TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/coverage-html
    reports:
      junit: $CI_PROJECT_DIR/junit.xml

Run notice scripts:
  <<: *test-default
  needs:
    - Build Engine
  script:
    - python -m unittest discover -s src/ -p notice*.py
  allow_failure: true


# Release stage
###############

.release-default: &release-default
  stage: release
  needs:
    - Lint Dockerfiles
    - Lint Python
    - Build Admin Application
    - Build Report Application
    - Build Engine
    - Build documentation
    - Test Admin Application
    - Test Engine
    - Test Report Application
  image: alpine
  variables:
    GIT_STRATEGY: none # We do not need the source code
  tags:
    - docker
  before_script:
    - apk add skopeo

# Rolling rc release:
.release-rc: &release-rc
  <<: *release-default
  rules:
    - if: $CI_COMMIT_REF_NAME == "development"
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_FROM}"
      "docker://${IMAGE_TO}:dev"

Release Report Application Candidate:
  <<: *release-rc
  variables:
    IMAGE_FROM: ${REPORT_IMAGE}
    IMAGE_TO: ${RELEASE_REPORT_IMAGE}

Release Admin Application Candidate:
  <<: *release-rc
  variables:
    IMAGE_FROM: ${ADMIN_IMAGE}
    IMAGE_TO: ${RELEASE_ADMIN_IMAGE}

Release Engine Candidate:
  <<: *release-rc
  variables:
    IMAGE_FROM: ${ENGINE_IMAGE}
    IMAGE_TO: ${RELEASE_ENGINE_IMAGE}


# Versioned release:
.release: &release
  <<: *release-default
  rules:
      # Matches <version core> from SemVer 2.0.0 BNF grammar. Ex. 2.3.4, but not 2.3.4-rc
      - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_FROM}"
      "docker://${IMAGE_TO}:${CI_COMMIT_TAG}"
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_FROM}"
      "docker://${IMAGE_TO}:latest"

Release Report Application:
  <<: *release
  variables:
    IMAGE_FROM: ${REPORT_IMAGE}
    IMAGE_TO: ${RELEASE_REPORT_IMAGE}

Release Admin Application:
  <<: *release
  variables:
    IMAGE_FROM: ${ADMIN_IMAGE}
    IMAGE_TO: ${RELEASE_ADMIN_IMAGE}

Release Engine:
  <<: *release
  variables:
    IMAGE_FROM: ${ENGINE_IMAGE}
    IMAGE_TO: ${RELEASE_ENGINE_IMAGE}
