version: '3.4'
services:
  db:
    image: postgres:12
    env_file:
      - dev-environment/db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-initdb.d/10-test-for-valid-env-variables.sh:/docker-entrypoint-initdb.d/10-test-for-valid-env-variables.sh
      - ./docker/postgres-initdb.d/20-create-admin-db-and-user.sh:/docker-entrypoint-initdb.d/20-create-admin-db-and-user.sh
      - ./docker/postgres-initdb.d/40-create-report-db-and-user.sh:/docker-entrypoint-initdb.d/40-create-report-db-and-user.sh
      # The following file adds the CREATEDB privilege to the db users to enable it
      # to run the django tests.
      # THIS SHOULD NOT BE USED IN PRODUCTION!!!
      - ./dev-environment/postgres-initdb.d/50-add-createdb-permissions.sh:/docker-entrypoint-initdb.d/50-add-createdb-permissions.sh

  queue:
    # Normally, we expect the `rabbitmq` image. The -management images come
    # with a set of management plugins installed and enabled by default.
    # They can be accessed through the web interface on port 15672 (or the port
    # it has been remapped to).
    # The credentials are given in the specified `rabbitmq.env` file.
    image: rabbitmq:3-management-alpine
    hostname: os2datascanner_msg_broker
    env_file:
      - dev-environment/rabbitmq.env
    ports:
      - "5672:5672"
      - "8030:15672"

  admin-frontend:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
      target: frontend
    volumes:
      - ./src/os2datascanner/projects/admin/adminapp/static/src:/code/src/os2datascanner/projects/admin/adminapp/static/src
      - frontend-bundles-admin:/code/src/os2datascanner/projects/admin/adminapp/static/dist/
      - /code/frontend/mode_modules

  report-frontend:
     build:
       context: .
       dockerfile: docker/report/Dockerfile
       target: frontend
     volumes:
       - ./src/os2datascanner/projects/report/reportapp/static/src:/code/src/os2datascanner/projects/report/reportapp/static/src
       - frontend-bundles-report:/code/src/os2datascanner/projects/report/reportapp/static/dist/
       - /code/frontend/mode_modules

  admin-application:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
      target: application
    env_file:
      - dev-environment/pika.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - frontend-bundles-admin:/code/src/os2datascanner/projects/admin/adminapp/static/dist/
      - ./dev-environment/admin/dev-settings.toml:/user-settings.toml
      - ./dev-environment/admin/.secret:/code/.secret
      - ./src/os2datascanner:/code/src/os2datascanner
    ports:
      - "8020:8000"
    depends_on:
      - db
      - admin-frontend
      - queue

  report-application:
    build:
      context: .
      dockerfile: docker/report/Dockerfile
      target: application
    env_file:
      - dev-environment/pika.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - frontend-bundles-report:/code/src/os2datascanner/projects/report/reportapp/static/dist/
      - ./dev-environment/report/dev-settings.toml:/user-settings.toml
      - ./src/os2datascanner:/code/src/os2datascanner
    ports:
      - "8040:8000"
    depends_on:
      - db
      - report-frontend
      - queue

  report-collector:
    build:
      context: .
      dockerfile: docker/report/Dockerfile
      target: application
    environment:
      - OS2DS_MIGRATE_MANUALLY=1
    env_file:
      - dev-environment/pika.env
    command: python manage.py pipeline_collector
    restart: unless-stopped
    volumes:
      - ./dev-environment/report/dev-settings.toml:/user-settings.toml
    depends_on:
      - db
      - report-application
      - queue

  engine_explorer:
    build:
      context: .
      dockerfile: docker/engine/Dockerfile
      target: engine
    env_file:
      - dev-environment/pika.env
    command: explorer --enable-metrics
    restart: unless-stopped
    depends_on:
      - queue

  engine_processor:
    build:
      context: .
      dockerfile: docker/engine/Dockerfile
      target: engine
    env_file:
      - dev-environment/pika.env
    command: processor --enable-metrics
    restart: unless-stopped
    depends_on:
      - queue

  engine_matcher:
    build:
      context: .
      dockerfile: docker/engine/Dockerfile
      target: engine
    env_file:
      - dev-environment/pika.env
    command: matcher --enable-metrics
    restart: unless-stopped
    depends_on:
      - queue

  engine_tagger:
    build:
      context: .
      dockerfile: docker/engine/Dockerfile
      target: engine
    env_file:
      - dev-environment/pika.env
    command: tagger --enable-metrics
    restart: unless-stopped
    depends_on:
      - queue

  engine_exporter:
    build:
      context: .
      dockerfile: docker/engine/Dockerfile
      target: engine
    env_file:
      - dev-environment/pika.env
    command: exporter --enable-metrics
    restart: unless-stopped
    depends_on:
      - queue

  prometheus:
    image: prom/prometheus
    volumes:
      - "./dev-environment/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "8050:9090"

  # default user is admin/admin
  grafana:
    image: grafana/grafana
    volumes:
      - "./dev-environment/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro"
      - "./dev-environment/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro"
    ports:
      - "8060:3000"


volumes:
  frontend-bundles-admin:
  frontend-bundles-report:
  postgres-data:
  postgres-initdb.d:
