# Generated by Django 2.2.4 on 2019-08-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('os2datascanner', '0015_remove_organization_lists')]

    operations = [
        migrations.AlterModelOptions(
            name='regexpattern',
            options={
                'ordering': ('pk', ),
                'verbose_name': 'Pattern'
            },
        )
    ]
