[mode]
debug = true
# Used for filescan and mounting
production = false

[site]
id = 1
# Site URL for calculating absolute URLs in emails.
url = "DEV_SITE"
allowed_hosts = []

secret_key = "DUMMYKEY(for development)DUMMYKEY(for development)"

[installation]
additional_apps = ["django_extextions"]

[scans]
enable_filescan = true
enable_webscan = true
enable_exchangescan = true

[databases]

    [databases.default]
    engine = "django.db.backends.postgresql_psycopg2"
    name = "os2datascanner_admin"
    user = "os2datascanner_admin_dev"
    password = "os2datascanner_admin_dev"
    host = "db"

[database_pool_args]
max_overflow = 10
pool_size = 5
recycle = 300

[email]
default_from_email = "os2datascanner@magenta.dk"
admin_email = "os2datascanner@magenta.dk"
host = "localhost"
port = 25
backend = "django.core.mail.backends.smtp.EmailBackend"
