SECRET_KEY = "DUMMYKEY(for testing)DUMMYKEY(for testing)"

[DATABASES]

    [DATABASES.default]
    ENGINE = "django.db.backends.postgresql_psycopg2"
    NAME = "os2datascanner"
    USER = "os2datascanner"
    PASSWORD = "os2datascanner"
    HOST = "postgres"

[dirs]
# These are the settings for various directories.
# Paths relative to the project directory should start with "*" while
# absolute paths should start with "/"
BUILD_DIR = ["*", "build"]
VAR_DIR = ["*", "var"]
LOGS_DIR = ["*", "var", "logs"]
MEDIA_ROOT = ["*", "uploads", "admin"]
TEST_OUTPUT_FILE_NAME = ["*", "build", "test-results.xml"]
DECRYPTION_FILE_PATH = ["/", "builds", "os2datascanner", "os2datascanner", "dev-environment", "admin"]